name: snekky

on: [push]

jobs:
  linux:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: krdlab/setup-haxe@v1
        with:
          haxe-version: 4.1.3
      - name: Install dependencies
        run: |
          haxelib install hxcpp
      - name: Build
        run: haxe build.hxml
      - name: Rename artifact
        run: mv cpp/SnekkyDecompiler cpp/snekkyd
      - name: Strip artifact symbols
        run: strip cpp/snekkyd
      - name: Upload artifact
        uses: actions/upload-artifact@v1
        with:
          name: snekkyd-linux
          path: cpp/snekkyd
  windows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
      - uses: krdlab/setup-haxe@v1
        with:
          haxe-version: 4.1.3
      - name: Install dependencies
        run: |
          haxelib install hxcpp
      - name: Build
        run: haxe build.hxml
      - name: Rename artifact
        run: | 
          cd cpp
          ren SnekkyDecompiler.exe snekkyd.exe
          cd ..
      - name: Strip artifact symbols
        run: strip cpp/snekkyd.exe
      - name: Upload artifact
        uses: actions/upload-artifact@v1
        with:
          name: snekkyd-win
          path: cpp/snekkyd.exe
  macos:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - uses: krdlab/setup-haxe@v1
        with:
          haxe-version: 4.1.3
      - name: Install dependencies
        run: |
          haxelib install hxcpp
      - name: Build
        run: haxe build.hxml
      - name: Rename artifact
        run: mv cpp/SnekkyDecompiler cpp/snekkyd
      - name: Strip artifact symbols
        run: strip cpp/snekkyd
      - name: Upload artifact
        uses: actions/upload-artifact@v1
        with:
          name: snekkyd-macos
          path: cpp/snekkyd
